# 1. Create a 3x3x3 array with random values 

In [74]:
import numpy as np
import pandas as pd

In [75]:
r_array=np.random.random((3,3,3))
r_array

array([[[0.00688209, 0.30910799, 0.8377331 ],
        [0.51606453, 0.58141752, 0.97261576],
        [0.09967222, 0.86949609, 0.69117621]],

       [[0.85263793, 0.99093215, 0.68620751],
        [0.57085706, 0.16664367, 0.04177137],
        [0.07310993, 0.06872991, 0.95316821]],

       [[0.47483675, 0.29427979, 0.88897195],
        [0.40208329, 0.86667506, 0.50252248],
        [0.29554279, 0.61676102, 0.83426258]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [77]:
a2=np.diag(1+np.arange(4),k=-1)
a2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [78]:
a3=np.zeros((8,8),dtype=int)
a3[1::2,0::2]=1
a3[::2,1::2]=1
a3

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [79]:
a4=np.random.random((5,5))
print('Before Normalization:')
print(a4)
print()
print('After Normalization:')
xmax,xmin=a4.max(),a4.min()
a4=(a4-xmax)/(xmax-xmin)
a4

Before Normalization:
[[0.63293287 0.21140445 0.30268871 0.76984702 0.6800998 ]
 [0.84550118 0.66273742 0.07326658 0.0071491  0.49608944]
 [0.98310517 0.45126039 0.11501577 0.12796332 0.32028283]
 [0.07343882 0.25146647 0.80660469 0.045569   0.8250007 ]
 [0.12466792 0.10690466 0.2619793  0.77620278 0.73017376]]

After Normalization:


array([[-0.35879925, -0.79071255, -0.69717939, -0.21851204, -0.3104703 ],
       [-0.14099404, -0.32826042, -0.93225363, -1.        , -0.49901398],
       [ 0.        , -0.54494745, -0.88947589, -0.87620936, -0.67915182],
       [-0.93207714, -0.74966356, -0.18084879, -0.96063357, -0.16199958],
       [-0.87958595, -0.89778683, -0.73889173, -0.2119997 , -0.2591627 ]])

# 5.  How to find common values between two arrays?

In [80]:
a5=np.arange(10)
a51=np.arange(6,15)
print('a5',a5)
print('a51',a51)
# Option one
common_values=[]
for i in a5:
    if i in a51:
        common_values.append(i)
print('common_values are',common_values)
# option two
print('common_values are',np.intersect1d(a5,a51))

a5 [0 1 2 3 4 5 6 7 8 9]
a51 [ 6  7  8  9 10 11 12 13 14]
common_values are [6, 7, 8, 9]
common_values are [6 7 8 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [81]:
Yesterday=np.datetime64('today','D')-np.timedelta64(1,"D")
print("Yesterday's date is:",Yesterday)
Today=np.datetime64('today','D')
print("Today's date is:", Today)
Tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("Tomorrow's date is:",Tomorrow)

Yesterday's date is: 2020-08-18
Today's date is: 2020-08-19
Tomorrow's date is: 2020-08-20


# 7. Consider two random array A and B, check if they are equal

In [82]:
a7=np.random.randint(0,10,5)
a71=np.random.randint(0,10,5)
print('a7 =',a7)
print('a71 =',a71)
equal=np.allclose(a7,a71)
print(equal)

a7 = [5 4 7 6 0]
a71 = [2 7 3 5 0]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [83]:
a8=np.random.random(10)
print(a8)
print()
print('Maximum value replaced by 0')
a81=a8[a8.argmax()]=0
a8

[0.71604245 0.14205679 0.47885722 0.71844373 0.95204665 0.99998321
 0.12308822 0.37485395 0.10102477 0.28983174]

Maximum value replaced by 0


array([0.71604245, 0.14205679, 0.47885722, 0.71844373, 0.95204665,
       0.        , 0.12308822, 0.37485395, 0.10102477, 0.28983174])

# 9. How to print all the values of an array?

# 10.Subtract the mean of each row of a matrix

In [84]:
a10=np.random.randint(0,20,size=(3,3))
print(a10)
print('Mean of rows are:',a10.mean(axis=1))
a10_1=a10-a10.mean(axis=1)
print(a10_1)

[[19  3 19]
 [ 4  7 15]
 [ 1 18 19]]
Mean of rows are: [13.66666667  8.66666667 12.66666667]
[[  5.33333333  -5.66666667   6.33333333]
 [ -9.66666667  -1.66666667   2.33333333]
 [-12.66666667   9.33333333   6.33333333]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [85]:
a11=np.ones((10))
print(a11)
a11_1=np.random.randint(0,len(a11),20)
print(a11_1)
a11+=np.bincount(a11_1,minlength=len(a11))
a11

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[9 8 3 9 3 2 8 3 0 5 1 0 3 2 0 4 5 1 3 4]


array([4., 3., 3., 6., 3., 3., 1., 1., 3., 3.])

# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [87]:
a13=np.random.randint(1,10,10)
print('a13',a13)
print('Most frequest value is:',np.bincount(a13).argmax())

a13 [1 5 6 2 8 7 2 6 3 2]
Most frequest value is: 2


# 14.How to get the n largest values of an array

In [88]:
a14=np.arange(1,51)
print('a14',a14)
n=5
print('n largest values of a14 are:',a14[-n:])

a14 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
n largest values of a14 are: [46 47 48 49 50]


# 15.How to create a record array from a regular array?

In [89]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
